from pydantic import Field
from typing import Literal

from schema.action.action import Action


class CodeAction(Action):
    language: Literal['git', 'go', 'glsl', 'assembly', 'racket', 'svelte', 'breadcrumbs', 'txt', 'velocity', 'python4', 'julia', 'yml', 'javasript', 'css', 'protobuf', 'rust', 'netlogo', 'hcl', 'scss', 'vb', 'http', 'sas', 'dart', 'vue', 'ejs', 'dockerfile', 'html', 'cypher', 'dockefile', 'vhdl', 'as3', 'c', 'ocaml', 'swift', 'apache', 'shell', 'groovy', 'matlab', 'gherkin', 'vtl', 'brainfuck', 'graphql', 'commandline', 'postgres', 'vbs', 'code', 'delphi', 'docker', 'toml', 'lua', 'r', 'pgsql', 'plsql', 'plaintext', 'cs', 'nginx', 'regex', 'pseudo', 'pseudo_rust', 'array', 'xslt', 'npm', 'proto', 'javascript', 'kotlin', 'react', 'verilog', 'cpp', 'bat', 'js', 'ts', 'asm', 'angular', 'terraform', 'mongodb', 'make', 'php', 'powershell', 'sh', 'sass', 'scala', 'xaml', 'lisp', 'asp', 'java', 'py', 'vba', 'vbnet', 'cmd', 'objc', 'pinescript', 'batch', 'solidity', 'mongo', 'actionscript', 'cmake', 'xml', 'svg', 'vbscript', 'python3', 'node', 'haskell', 'sqlite', 'less', 'jquery', 'yaml', 'typescript', 'prolog', 'pseudocode', 'python', 'ini', 'golang', 'perl', 'applescript', 'bash', 'cython', 's', 'mdx', 'json', 'javascipt', 'ruby', 'cql', 'tsx', 'mysql', 'csharp', 'jenkins', 'jsx', 'fsharp', 'gradle', 'pseudo_code', 'latex', 'openqasm', 'output', 'pascal', 'sql', 'text', 'xpath', 'jsp', 'fortran', 'makefile', 'puppet', 'tex', 'thrift', 'twig', 'markdown', 'idris', 
    "systemverilog", "troff", "console", "nit", "cad", "gp", "rdf", "scad", "kconfig", "conf", "redis", "bison", "smarty", "vim", "vcard", "llvm",
    "qml",
    "swig",
    "xyz",
    "coffeescript",
    "rst",
    "xbasic",
    "eigenmath",
    "properties",
    "gap",
    "groff",
    "wolfram",
    "futura",
    "scilab",
    "env",
    "cafeobj",
    "yang",
    "forth",
    "buildx",
    "bibtex",
    "gnuplot",
    "xhtml",
    "stata",
    "moonscript",
    "dsl",
    "ics",
    "math",
    "dts",
    "quantum",
    "xpp",
    "cfg",
    "jags",
    "ada",
    "plpgsql",
    "agda",
    "p4",
    "arduino",
    "doxygen",
    "objectscript",
    "sparql",
    "autohotkey",
    "cil",
    "language",
    "rest",
    "gamescript",
    "smile",
    "jl",
    "excel",
    "coldfusion",
    "liquid",
    "hocon",
    "arm",
    "tlbuild",
    "sonnet",
    "blade",
    "aspx",
    "hypothetical",
    "dtd",
    "jldoctest",
    "lean",
    "genetic",
    "pari",
    "targetlang",
    "basic",
    "cfml",
    "turtle",
    "cobol",
    "pddl",
    "mermaid",
    "maxmsp",
    "nix",
    "powerapps",
    "cabal",
    "sage",
    "ld",
    "qmake",
    "sml",
    "coq",
    "afl",
    "octave",
    "simpli",
    "gml",
    "maple",
    "aql",
    "pro",
    "ps",
    "erb",
    "batchfile",
    "m4",
    "idl",
    "plantuml",
    "diff",
    "flatbuffers",
    "django",
    "targetql",
    "qlik",
    "shakespeare",
    "dotenv",
    "hlsl",
    "ourcodelang",
    "dax",
    "erlang",
    "isabelle",
    "elisp",
    "mathematica",
    "jinja",
    "cisco",
    "nsis",
    "chapel",
    "meson",
    "elixir",
    "handlebars",
    "mumps",
    "phpt",
    "d",
    "qsharp",
    "csv",
    "euler",
    "tomail",
    "hol",
    "sagemath",
    "husk",
    "ceylon",
    "stan",
    "postgresql",
    "hscript",
    "clojure",
    "usql",
    "voxelscript",
    "scificode",
    "scheme",
    "wasm",
    "asciidoc",
    "awk",
    "nasm",
    "sm",
    "restructuredtext",
    "flux",
    "freemarker",
    "smalltalk",
    "obscuria",
    "cuda",
    "ml"] = Field(
        ..., description="The language of the code to execute" # code_feedback is multilingual
    )
    content: str = Field(..., description="The code to execute")
    description: str | None = Field(
        ..., description="The description/thought provided for the action"
    )

